// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFLSw2gmMpKSXGb-AqujnfVsdMWC-Gk6w',
    appId: '1:326894203146:web:82789eadad19786dde8af3',
    messagingSenderId: '326894203146',
    projectId: 'quanlysanpham-2f4b4',
    authDomain: 'quanlysanpham-2f4b4.firebaseapp.com',
    storageBucket: 'quanlysanpham-2f4b4.firebasestorage.app',
    measurementId: 'G-6V0NP53VQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNO7M9tqdBKEuDyl-33igMF4KOH8m_Hcg',
    appId: '1:326894203146:android:8f4cdc70d29ee168de8af3',
    messagingSenderId: '326894203146',
    projectId: 'quanlysanpham-2f4b4',
    storageBucket: 'quanlysanpham-2f4b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkWuk1hJzl57ExDfJfhYzKCD6Y1gDF7Xo',
    appId: '1:326894203146:ios:2d28d829322b23b1de8af3',
    messagingSenderId: '326894203146',
    projectId: 'quanlysanpham-2f4b4',
    storageBucket: 'quanlysanpham-2f4b4.firebasestorage.app',
    iosBundleId: 'com.example.quanLySanPham',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkWuk1hJzl57ExDfJfhYzKCD6Y1gDF7Xo',
    appId: '1:326894203146:ios:2d28d829322b23b1de8af3',
    messagingSenderId: '326894203146',
    projectId: 'quanlysanpham-2f4b4',
    storageBucket: 'quanlysanpham-2f4b4.firebasestorage.app',
    iosBundleId: 'com.example.quanLySanPham',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFLSw2gmMpKSXGb-AqujnfVsdMWC-Gk6w',
    appId: '1:326894203146:web:d375ca536f3043b2de8af3',
    messagingSenderId: '326894203146',
    projectId: 'quanlysanpham-2f4b4',
    authDomain: 'quanlysanpham-2f4b4.firebaseapp.com',
    storageBucket: 'quanlysanpham-2f4b4.firebasestorage.app',
    measurementId: 'G-68E1SDBQD9',
  );
}
